name: Manual Workflow

on: 
  workflow_dispatch: 
    inputs: 
      param1: 
        description: 'Parameter 1'
        required: true
      param2:
        description: 'Parameter 2'
        required: false
        
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Print Input Parameters
      run: |
        echo "Parameter 1: ${{ github.event.inputs.param1 }}"
        echo "Parameter 2: ${{ github.event.inputs.param2 }}"
        
  
