name: Webflow to AWS Amazion Website

on:
  workflow_dispatch: # Manually trigger the workflow from GitHub Actions tab

jobs:
  run_powershell_script:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run PowerShell script
      run: |
        if ($host.UI.RawUI -ne $null -and $host.UI.RawUI.SupportsVirtualTerminal) {$RawUI.CursorPosition = @{X=0;Y=0}}
        ./publisher.ps1
      shell: pwsh
