name: Scrape Website and Push Data

on:
  workflow_dispatch: # Manually trigger the workflow from GitHub Actions tab
  schedule:
    - cron: '0 0 * * *' # Run the workflow every day at midnight (UTC)

jobs:
  scrape_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Assuming you have a requirements.txt file with necessary libraries

    - name: Scrape data
      run: |
        python scraper.py

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Set up SSH
      run: |
        echo "${{ secrets.REPO_SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global core.sshCommand "ssh -i $(pwd)/private_key -o UserKnownHostsFile=~/.ssh/known_hosts"

    - name: Commit and push data
      run: |
        git add data.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update data.json with new scraped data"
        git remote set-url origin git@github.com:gabeungureanu/safelite-webflow.git
        git push
